version: "3.9"

services:
  web:
    image: nginx:latest
    ports:
      - "6081:80"
      - "6083:443"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./localhost.crt:/etc/nginx/ssl/example.com.crt
      - ./localhost.key:/etc/nginx/ssl/example.com.key
    links:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: php-dockerfile
    volumes:
      - ./src:/var/www/html
    links:
      - db-mysql
  db-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tutorial
      MYSQL_USER: tutorial
      MYSQL_PASSWORD: secret
    ports:
      - "9906:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
  db-postgre:
    image: postgres
    ports:
      - "9932:5432"
    environment:
      POSTGRES_USER: tutorial
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tutorial
    volumes:
      - ./postgre-data:/var/lib/postgres
